language: node_js
node_js:
  - "8.11"
install:
  - npm install
script:
  - npm test
addons:
  - chrome: stable
before-install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before-script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"